### ISSUE TITLE
Determine initial scope of graph

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/nulecule#10]
Currently there's a simple list that defines the "graph." Is this sufficient for the initial v1 proposal?

**Comment by vpavlin** [comment]
I think the answer is yes. The only problem I see at the moment is specifying correct app image - i.e. `mariadb-app` leads to `docker.io/library/mariadb-app`. To say you want something else, you need to specify it as `myrepo/app_name`, which might be fine, although I find nesting more readable in this case:

```
{
  "repository": "myrepo",
  "name": "app_name"
}
```

and automatically enables us to extend in future

```
{
  "repository": "myrepo",
  "name": "app_name",
  "after": ["some_app", "another_app"],
},
{
  "repository": "somerepo",
  "name": "some_app"
}
...
```

Which could be a simple solution for implementation of full graph
