### ISSUE TITLE
tag name of releases use v-notation

### ISSUE THREAD

**Issue by goern** [projectatomic/nulecule#116]
vx.y.z is only used for the release tags and archives, but not anywhere else in the spec. We should normalize that and retag without the `v`

**Comment by aweiteka** [comment]
Is this a big deal? I'm just using inline guidance from GitHub when you create a tag.

```
Tagging suggestions

It’s common practice to prefix your 
version names with the letter v.
Some good tag names might be v1.0 
or v2.3.4. 
```

**Comment by goern** [comment]
no, not a big deal, I just wanted to avoid confusion|mismatch and was not aware that github thinks that it is a common practice
