### ISSUE TITLE
Make json spec valid

### ISSUE THREAD

**Issue by jayunit100** [projectatomic/nulecule#12]
default impl uses invalid json...

```
 "replicas": REPLICAS 
```

so, to fix this ... we need to do 3 things: 
1. define the json schema to be valid 
2. add the json files into this repo (right now theyre empty). invalid json is impossible to format using std json tools. 
3. update the impl  https://github.com/vpavlin/atomicapp-run/issues/4, to implement that spec.

**Comment by aweiteka** [comment]
Current v0.0.1-alph is valid json.
