### ISSUE TITLE
Expand OpenShift provider examples

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/nulecule#125]
We currently have no OpenShift provider examples. The only example we have is via inherit[1]. We need at least one example using a simple template to fully test the openshift provider.

[1] https://github.com/projectatomic/nulecule/blob/master/examples/mysql-centos7-atomicapp/Nulecule

**Comment by goern** [comment]
I have started some, but it is untested, I am happy if someone picks it up: https://github.com/goern/atomicapp-spec/blob/examples/wordpressplusplus/examples/wordpress-centos7-atomicapp/Nulecule

**Comment by goern** [comment]
examples move to https://github.com/projectatomic/nulecule-library
