### ISSUE TITLE
remove skydns example

### ISSUE THREAD

**Issue by goern** [projectatomic/nulecule#131]
Any objections? It does not show something in addition to the other examples and I cant figure out if it was used by any other example.

**Comment by vpavlin** [comment]
See WP example: https://github.com/projectatomic/nulecule/blob/master/examples/wordpress-centos7-atomicapp/Nulecule#L12

**Comment by goern** [comment]
yeah, thats mine :) and it doesnt required skydns, there is in PR coming in

**Comment by bexelbie** [comment]
The nice thing about the WP example, prior to this PR is that it shows building a nulecule from other nulecules

**Comment by goern** [comment]
Still true, as I reuse mariadb/mysql Atomic App

**Comment by goern** [comment]
examples move to https://github.com/projectatomic/nulecule-library
