### ISSUE TITLE
We need more descriptive problem statement for Nulecule

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/nulecule#159]
The current problem statement [1] is not easy to understand for people new to docker and Linux containers. If we can explain it more , it will be helpful.  This video is a good point to start https://www.youtube.com/watch?v=in2Y4HcDp-s&feature=share

[1] https://github.com/projectatomic/nulecule#problem-statement

**Comment by ghost** [comment]
Proposal in https://github.com/projectatomic/nulecule/pull/174
