### ISSUE TITLE
How to define providers and extensions

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/nulecule#18]
How much do we need to define for specific providers and extensions? Are these defined externally to the spec or does it need to be consolidated here?

**Comment by tradej** [comment]
I believe there should indeed be an easy way to add information for other programs, e. g. in a form of extensions, mentioned in the spec. For example making it a requirement in the spec that parsing mustn't be strict should prevent a lot of problems with extensibility in the future IMO.

Speaking from the point of DevAssistant, we are very open to taking as much metadata from the Atomicfile as possible - this makes the maintenance easier for the upstream developer. However, we would appreciate having the possibility to have some bits of information in the Atomicfile too. A concrete example of what we may need is a freeform field in the Atomicfile where we can link DevAssistant-specific files (those are stored elsewhere in the tree), and maybe add some other information not useful to other consumers of the Atomicfile.

**Comment by aweiteka** [comment]
@tradej is this question satisfied for now? Can we close?

**Comment by tradej** [comment]
Yes, the spec allows for additional metadata, so I believe this is okay.
