### ISSUE TITLE
Our examples should be using yml not json.

### ISSUE THREAD

**Issue by cdrage** [projectatomic/nulecule#188]
Within the /spec folder I believe we should be using yaml examples rather than json as it's the go-to format when we do our blog-posting as well as our implementation.

Thoughts?

**Comment by goern** [comment]
aint that just empty files?

**Comment by cdrage** [comment]
@goern nah, just most example (nulecule-library, etc.) use .yaml files instead for defining graph, Nulecule, etc. Shouldn't we reflect the spec to be the same?

yaml looks _much_ cleaner imo

**Comment by goern** [comment]
ah :) actually the Nulecule Specification defines that the formats that could be used are JSON or YAML. What is the rational to remove one of these and reduce freedom of choice?

**Comment by cdrage** [comment]
For cleaner reading and ease of introduction  :) We're not removing it, we'll just convert them to yaml. 

edit: we already tell the user they can use ini, yaml or json for Nulecule / graphs / etc.

**Comment by goern** [comment]
I would like to keep both, as I personally dont like YAML ;) 

other opinion?

**Comment by vpavlin** [comment]
I like YAML:P But I still see the benefit of presenting user with both versions.
