### ISSUE TITLE
Maintainers and PR review

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/nulecule#19]
We need to ensure changes to the spec are reviewed carefully and consider impact to implementations.

@goern would you be able to review pull requests?
@vpavlin would you be able to review pull requests?

**Comment by goern** [comment]
ACK

**Comment by langdon** [comment]
Fixed up the perms to make @goern, @vpavlin, @aweiteka committers in a group called nulecule (in case we need more projects later).

**Comment by aweiteka** [comment]
@whitel thanks!

**Comment by vpavlin** [comment]
ACK
