### ISSUE TITLE
$hostport should be "$hostport"

### ISSUE THREAD

**Issue by cdrage** [projectatomic/nulecule#192]
Run `nulecule/examples/helloapache/artifacts/kubernetes/hello-apache-pod.json` through jsonlint and you'll see that it's invalid.

One of the reasons being is that for numeric values that are filled in with a param, we do not add any quotes. 

Adding quotes to this makes the json/haml valid and does not harm deployment via Kubernetes, OpenShift, etcetera, as the respective programs convert the string value regardless.

I believe, for example: $hostport should be "$hostport" within examples and such. This will allow programs such as a json to yaml converter be able to easily validate and convert such objects.

**Comment by dustymabe** [comment]
we need to remove the examples from this github repo. They have been moved to nulecule-library.

**Comment by dustymabe** [comment]
please open against nulecule-library
