### ISSUE TITLE
Examples should be removed

### ISSUE THREAD

**Issue by cdrage** [projectatomic/nulecule#194]
With nulecule-library created, the examples dir here should be removed and instead pointed to github.com/projectatomic/nulecule-library

hub.docker.com should sync with any PRs / changes to projectatomic/nulecule-library instead of the current examples directory here.

**Comment by goern** [comment]
full_ack, anyone going to do work on #162 so that the specification has one good uber-example?

**Comment by cdrage** [comment]
@goern 
looks like a lot of people have been focusing on getting this past GA instead of the uber-example. Can we merge #195 regardless and have a "helloworld" example within nulecule-library (modified helloapache).

Otherwise, we should template what our uber example should be.

redis-cluster with resque / ruby on rails / bunch of other load-balancing ish stuff? we should have a look at some robust kubernetes examples that incorporate load-balancing and the removal / scaling of containers for each application.
