### ISSUE TITLE
mariadb-fedora-atomicapp `artifacts` directory named as `graph`

### ISSUE THREAD

**Issue by surajssd** [projectatomic/nulecule#197]
[`mariadb-fedora-atomicapp`](https://github.com/projectatomic/nulecule/tree/master/examples/mariadb-fedora-atomicapp) example has `artifacts` directory named as `graph`, which causes the `atomicapp` to fail. By default the directory be named as `artifacts`, so that it is easy for the beginner to use it without having to change any configurations.

**Comment by goern** [comment]
Is this considered a bug or a usability issue? If it is a bug (atomicapp requires the directory to be called artifacts) than you should fix atomicapp, and not simply rename the directory.

**Comment by LalatenduMohanty** [comment]
I think it is an usability/user experience issue from Nulecule point of view. For example https://github.com/projectatomic/nulecule/blob/master/docs/getting-started.md tells you to create artifacts directory

**Comment by LalatenduMohanty** [comment]
@surajssd BTW the examples are now maintained at https://github.com/projectatomic/nulecule-library/.
For mariadb-fedora-atomicapp I can see artifacts directory in 
https://github.com/projectatomic/nulecule-library/tree/master/mariadb-fedora-atomicapp

**Comment by surajssd** [comment]
@LalatenduMohanty @goern 
This issue is no longer valid it seems, and can be closed and this [issue#194](https://github.com/projectatomic/nulecule/issues/194) be resolved as soon as possible.

**Comment by goern** [comment]
see also #162
