### ISSUE TITLE
Get back the definition of files the nulecule app consists of

### ISSUE THREAD

**Issue by vpavlin** [projectatomic/nulecule#45]
With the move to the JSON Schema we lost the definition of files/dirs and it's content which was previously specified in the `schema.json`. I think it was useful - for example generation of `Dockerfile` was very easy that with it. Can we think about where/how to specify it again?

**Comment by goern** [comment]
has this been fixed?

**Comment by vpavlin** [comment]
no

**Comment by tradej** [comment]
Am I understanding the issue correctly, believing that we want to store information about what the allowed layout of the filesystem is?

Examples:

_Allowed layout_

```
/Nulecule
/Dockerfile
/artifacts/kubernetes/k8s.json
```

_Disallowed layouts_

```
/nulecule
/Dockerfile
```

```
/Nulecule
/artifacts/k8s.json
```

**Comment by vpavlin** [comment]
Sort of...I would skip artifacts dir, but I think that following should be required:

```
/nulecule
/README.*
/Dockerfile
```

**Comment by tradej** [comment]
Can we then just put somewhere a list of (expandable) filenames that will be tested for existence with e. g. `test -f` or `os.path.isfile`? Additionally, entries ending with a slash could be understood as directories and handled appropriately.

This approach would work only as an implication, i. e. it wouldn't forbid files from residing somewhere, only mandate that some other files do. Is that the desired behaviour?

**Comment by goern** [comment]
Ja, `Nulecule` is a required file and must carry a JSON or YAML formated Nulecule compliant description of an Application, `Dockerfile` is required and must declare all files that need to be packaged as a docker image. `README.md` is optional and may contain a human readable description of the Application.

**Comment by tradej** [comment]
Yes, Christoph, I understand that. My question is if we want:

1) Only to check if `/Dockerfile`, `/Nulecule` and `/README.*` exist
2) Also forbid/warn about the existence of some files, like `/nulecule` or `/artifacts/not-a-dirname.json`

**Comment by vpavlin** [comment]
I think warning like `This app containes some unnecessary files` would be nice in case of DevAssistant usage, but the spec should only care about files we need - i.e. `Nulecule` and `Dockerfile` (and potentially `README.md`..

**Comment by tradej** [comment]
See the linked PR for solution.
