### ISSUE TITLE
Rename Atomicfile

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/nulecule#6]
`Atomicfile` is an interesting name but too specific to project atomic. As a specification we need another filename.

**Comment by vpavlin** [comment]
IMO depends heavily on #8

**Comment by vpavlin** [comment]
Are we going to rename to Nulecule? Or Nulecule.yaml or...?

**Comment by langdon** [comment]
The proposal on the call this (my) morning was "nulecule" (no extension, lowercase)

**Comment by vpavlin** [comment]
Sounds good to me

**Comment by aweiteka** [comment]
-1 on nulecule. IMO it's just a silly name for a spec, not something devs should have to know how to spell.

What's wrong with `template.yaml` or `template.json`?

**Comment by vpavlin** [comment]
Does the word `template` realy describe that it's an app definition? Also let's keep it extension agnostic, if possible..

What about just a file called `nc`?

**Comment by goern** [comment]
So it's `Atomicfile` for historical reason, `nulecule` because we-1 like it ... but why lowercase?

**Comment by ncoghlan** [comment]
I have to weigh in with a "What?" reaction to "nulecule". I know naming things is hard, but that one's taking the made up words thing too far :)

Could we perhaps instead opt for something boringly descriptive like "Deployment.yaml"? (referred to as a "deployment file")

**Comment by tradej** [comment]
-1 to `[Nn]ulecule`. While it's cute as a project name/trademark, it should be obvious even to unaffiliated people what the file contains. `deployment.yaml` looks reasonable, I suggest `application.yaml` (`app.yaml` is widely used by Google).

**Comment by goern** [comment]
so lets make it a list of files that are valid: nulecule, Nulecule, Atomicfile, deployment.yaml, app.yaml, application.yaml

**Comment by vpavlin** [comment]
Any ideas how to close this?Schema references Atomicfile, containerapp uses nuleculefile atm...

**Comment by johnmark** [comment]
Can we just go with app.yaml? Nulecule is just a spec, not an implementation. -1 on nulecule.

**Comment by goern** [comment]
I think app.yaml is pretty collision prone, it could be some left over artifact from a lazy ISV that just build a Nulecule compliant Atomicapp layered image...
Why dont we make it a list of valid and checked filenames? Something like: nulecule, Nulecule, Atomicfile, deployment.yaml, app.yaml, application.yaml ...

**Comment by ncoghlan** [comment]
We need to pick one to use in examples, reference projects, etc. Being permissive just breeds confusion where there doesn't need to be any.

For me, the key thing we're describing in the spec is how to _deploy_ the application, moreso than defining the application itself. In particular, we're parameterising that description, so different deployments can readily tailor it to their environment without needing to rewrite it from scratch.

This is why I like "deployment.yaml" - the intent of the file is to explain how to get from a static pile of source code and other artifacts to a deployed, running service, whether on a developer's system or in a production environment.

**Comment by tradej** [comment]
I agree with only one name being recognized. Shall we have a poll to establish which one it should be?

**Comment by goern** [comment]
as of the container-tools standup today, we call the manifest file, that described how to deploy: `nulecule`
