### ISSUE TITLE
Consider how environment variables will be supported

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/nulecule#7]
Many applications rely on environment variables. We need to consider what mechanism will support this and incorporate into `params.conf`.

**Comment by vpavlin** [comment]
I am not sure if I understand this correctly - is the question "How to use env vars to override params.conf?", or "How to set environment variables from params.conf?"

I guess the former..then I can imagine

component params.conf -> app params.conf -> environment variables -> answers file (this end is what the app uses in the end)

Variables could be in form:

```
COMPONENT_PARAM = VALUE
MARIADBAPP_PASSWORD = "mypass"
```

**Comment by aweiteka** [comment]
This issue has not actually come up yet in any known example. Closing.
