### ISSUE TITLE
Rename specification repository

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/nulecule#8]
"containerapp-spec" is probably not a good name. It's too similar to AWS' [AppSpec](http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html) and CoreOS' [App Container Spec](https://github.com/appc/spec/), which is the basis for Rocket.

**Comment by vpavlin** [comment]
What about something mentioning "deployment" because the main content of the app image is a description of how to deploy this particular app (f.e. k8s files)

**Comment by aweiteka** [comment]
[Nulecule](http://simpsons.wikia.com/wiki/Made-up_words)!

**Comment by aweiteka** [comment]
Based on initial feedback, the name **nulecule** isn't working on so many levels.

**Comment by aweiteka** [comment]
Further discussion... we'll stick with **Nulecule**, expecting implementations to use their own terminology. For example, Atomic host will reference "Atomic App". Nulecule is just a spec, not an implementation that end-users will only reference for development purposes.
