### ISSUE TITLE
Use list of Providers instead of magic key naming

### ISSUE THREAD

**Issue by goern** [projectatomic/nulecule#81]
Rework the spec the same way we did it with #35 so that we can fix https://github.com/projectatomic/nulecule/issues/70

**Comment by aweiteka** [comment]
I'm okay with how it is: the provider keys _are_ magical.

**Comment by goern** [comment]
@tradej  @vpavlin any opinion?

**Comment by tradej** [comment]
Since we intend to support a limited number of providers with non-overlapping names, I'm also in favour of the status quo.

**Comment by vpavlin** [comment]
I am definitely in favour of making my life easier and using current structure.
